---
name: Builder

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} add-on
    strategy:
      matrix:
        arch: ["aarch64", "amd64"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build add-on
        uses: home-assistant/builder@2025.09.0
        with:
          args: |
            --${{ matrix.arch }} \
            --image "${{ matrix.arch }}-ha_enoceanmqtt-addon" \
            --target /data/addon \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
